version: "3"

services:
  server:
    container_name: server_hive
    build: ./Back/server
    ports:
      - 5000:5000
    image: server_image_hive
    volumes:
      - venv:/venv
  client:
    container_name: client_hive
    build: ./Front
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:
      - node_modules:/node_modules
    restart: always

volumes:
  venv:
  node_modules:
